# Generated by Django 4.0.5 on 2022-06-21 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_options_alter_studentgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studentgroup', verbose_name='Группа N'),
        ),
    ]
