# Generated by Django 4.0.5 on 2022-06-27 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.subject', verbose_name='Группа N:'),
        ),
    ]
