# Generated by Django 4.0.5 on 2022-06-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_studentgroup_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgroup',
            old_name='subject',
            new_name='subjects',
        ),
    ]
